name: Black Code Format Check

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Black
      run: pip install black
    
    - name: Check code formatting with Black
      run: black --check --diff .